"""add restaurant profile bootstrap from clover schema

Revision ID: 2ae7e5a3d715
Revises: dc31a1741fd8
Create Date: 2026-08-26 13:42:30.549502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ae7e5a3d715'
down_revision: Union[str, Sequence[str], None] = 'dc31a1741fd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_bootstrap_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_bootstrap_runs_restaurant_id'), 'profile_bootstrap_runs', ['restaurant_id'], unique=False)
    op.create_table('restaurant_profile_source_controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('managed_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('snapshot_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_profile_source_controls_restaurant_source', 'restaurant_profile_source_controls', ['restaurant_id', 'source_system_id'], unique=False)
    op.create_index(op.f('ix_restaurant_profile_source_controls_restaurant_id'), 'restaurant_profile_source_controls', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_restaurant_profile_source_controls_source_system_id'), 'restaurant_profile_source_controls', ['source_system_id'], unique=False)
    op.create_table('source_role_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('source_role_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_role_id', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mapping_status', sa.String(length=32), nullable=False),
    sa.Column('mapping_source', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['restaurant_role_id'], ['restaurant_roles.id'], ),
    sa.ForeignKeyConstraint(['source_role_id'], ['source_roles.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'source_role_id', 'valid_from')
    )
    op.create_index(op.f('ix_source_role_mappings_restaurant_id'), 'source_role_mappings', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_source_role_mappings_restaurant_role_id'), 'source_role_mappings', ['restaurant_role_id'], unique=False)
    op.create_index('ix_source_role_mappings_restaurant_source_role', 'source_role_mappings', ['restaurant_id', 'source_role_id'], unique=False)
    op.create_index(op.f('ix_source_role_mappings_source_role_id'), 'source_role_mappings', ['source_role_id'], unique=False)
    op.create_table('restaurant_profile_reconciliation_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bootstrap_run_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('issue_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('source_role_id', sa.Integer(), nullable=True),
    sa.Column('restaurant_role_id', sa.Integer(), nullable=True),
    sa.Column('mapping_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bootstrap_run_id'], ['profile_bootstrap_runs.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['mapping_id'], ['source_role_mappings.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['restaurant_role_id'], ['restaurant_roles.id'], ),
    sa.ForeignKeyConstraint(['source_role_id'], ['source_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_profile_reconciliation_issues_bootstrap_run_id'), 'restaurant_profile_reconciliation_issues', ['bootstrap_run_id'], unique=False)
    op.create_index(op.f('ix_restaurant_profile_reconciliation_issues_restaurant_id'), 'restaurant_profile_reconciliation_issues', ['restaurant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurant_profile_reconciliation_issues_restaurant_id'), table_name='restaurant_profile_reconciliation_issues')
    op.drop_index(op.f('ix_restaurant_profile_reconciliation_issues_bootstrap_run_id'), table_name='restaurant_profile_reconciliation_issues')
    op.drop_table('restaurant_profile_reconciliation_issues')
    op.drop_index(op.f('ix_source_role_mappings_source_role_id'), table_name='source_role_mappings')
    op.drop_index('ix_source_role_mappings_restaurant_source_role', table_name='source_role_mappings')
    op.drop_index(op.f('ix_source_role_mappings_restaurant_role_id'), table_name='source_role_mappings')
    op.drop_index(op.f('ix_source_role_mappings_restaurant_id'), table_name='source_role_mappings')
    op.drop_table('source_role_mappings')
    op.drop_index(op.f('ix_restaurant_profile_source_controls_source_system_id'), table_name='restaurant_profile_source_controls')
    op.drop_index(op.f('ix_restaurant_profile_source_controls_restaurant_id'), table_name='restaurant_profile_source_controls')
    op.drop_index('ix_profile_source_controls_restaurant_source', table_name='restaurant_profile_source_controls')
    op.drop_table('restaurant_profile_source_controls')
    op.drop_index(op.f('ix_profile_bootstrap_runs_restaurant_id'), table_name='profile_bootstrap_runs')
    op.drop_table('profile_bootstrap_runs')
    # ### end Alembic commands ###
