"""add overtime rule matrix foundation

Revision ID: 2b29002fe5c5
Revises: 4027ebe90941
Create Date: 2026-09-08 19:43:23.177801

Adds `overtime_rules` — the canonical Overtime Rule Matrix foundation
(Product Owner decision). Stores WHAT a statutory overtime rule is
(jurisdiction, scope, thresholds, total rate multiplier, regular-rate
method, overlap method, effective dating, status) — no overtime is
calculated by this migration or by any code in this repository. See
`OvertimeRule`'s own docstring in `rfone_data_store/models.py` and
`01 Domains/Cross Domain/Personnel Management/Payroll/
OVERTIME_RULE_MATRIX_001.md` for the full functional boundary.

Deliberately not attached to `LegalEntity`, `restaurants`, or any other
existing table — jurisdiction is a separate dimension from employer
identity, and no other table needs to reference this one yet.

Autogenerate also detected pre-existing, unrelated drift on Selection tables
(`applications`, `in_person_interview_plans`, `phone_interview_plans`) —
those are intentionally NOT included here; this migration only adds the
`overtime_rules` table.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b29002fe5c5'
down_revision: Union[str, Sequence[str], None] = '4027ebe90941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overtime_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('jurisdiction_level', sa.String(length=16), nullable=False),
    sa.Column('jurisdiction_code', sa.String(length=16), nullable=False),
    sa.Column('rule_scope', sa.String(length=32), nullable=False),
    sa.Column('threshold_hours', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('threshold_day_number', sa.Integer(), nullable=True),
    sa.Column('total_rate_multiplier', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('regular_rate_method', sa.String(length=32), nullable=False),
    sa.Column('overlap_method', sa.String(length=32), nullable=False),
    sa.Column('employee_classification', sa.String(length=64), nullable=True),
    sa.Column('industry_code', sa.String(length=32), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("jurisdiction_level IN ('FEDERAL', 'STATE', 'LOCAL')", name='ck_overtime_rules_jurisdiction_level'),
    sa.CheckConstraint("overlap_method IN ('NON_STACKING_MAXIMUM', 'STACKING', 'INDEPENDENT')", name='ck_overtime_rules_overlap_method'),
    sa.CheckConstraint("regular_rate_method IN ('WEIGHTED_REGULAR_RATE', 'RATE_IN_EFFECT', 'NOT_APPLICABLE')", name='ck_overtime_rules_regular_rate_method'),
    sa.CheckConstraint("rule_scope IN ('WORKWEEK', 'WORKDAY', 'CONSECUTIVE_HOURS', 'CONSECUTIVE_DAY')", name='ck_overtime_rules_rule_scope'),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name='ck_overtime_rules_status'),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='ck_overtime_rules_effective_range'),
    sa.CheckConstraint('threshold_day_number IS NULL OR threshold_day_number > 0', name='ck_overtime_rules_threshold_day_number'),
    sa.CheckConstraint('threshold_hours IS NULL OR threshold_hours >= 0', name='ck_overtime_rules_threshold_hours'),
    sa.CheckConstraint('total_rate_multiplier >= 1', name='ck_overtime_rules_total_rate_multiplier'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('overtime_rules')
    # ### end Alembic commands ###
