"""add payroll schema

Revision ID: 47b3d9bb8108
Revises: 2ae7e5a3d715
Create Date: 2026-08-27 06:12:10.209144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47b3d9bb8108'
down_revision: Union[str, Sequence[str], None] = '2ae7e5a3d715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('schedule_type', sa.String(length=16), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'code')
    )
    op.create_index(op.f('ix_payroll_schedules_restaurant_id'), 'payroll_schedules', ['restaurant_id'], unique=False)
    op.create_table('workweek_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('start_weekday', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workweek_definitions_restaurant_id'), 'workweek_definitions', ['restaurant_id'], unique=False)
    op.create_table('payroll_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('payroll_schedule_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pay_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_type', sa.String(length=16), nullable=False),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('superseded_by_payroll_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['payroll_schedule_id'], ['payroll_schedules.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_payroll_run_id'], ['payroll_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_runs_restaurant_id'), 'payroll_runs', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_payroll_runs_source_system_id'), 'payroll_runs', ['source_system_id'], unique=False)
    op.create_table('payroll_import_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('payroll_run_id', sa.Integer(), nullable=True),
    sa.Column('source_file_name', sa.String(length=255), nullable=False),
    sa.Column('source_file_hash', sa.String(length=128), nullable=False),
    sa.Column('supersedes_import_run_id', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('employees_represented_count', sa.Integer(), nullable=True),
    sa.Column('unresolved_employee_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.ForeignKeyConstraint(['supersedes_import_run_id'], ['payroll_import_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system_id', 'restaurant_id', 'source_file_hash')
    )
    op.create_index(op.f('ix_payroll_import_runs_restaurant_id'), 'payroll_import_runs', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_payroll_import_runs_source_system_id'), 'payroll_import_runs', ['source_system_id'], unique=False)
    op.create_table('employee_compensation_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('function_label', sa.String(length=255), nullable=False),
    sa.Column('restaurant_role_id', sa.Integer(), nullable=True),
    sa.Column('compensation_basis', sa.String(length=16), nullable=False),
    sa.Column('hourly_rate_minor', sa.Integer(), nullable=True),
    sa.Column('salaried_period_amount_minor', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(compensation_basis = 'HOURLY' AND hourly_rate_minor IS NOT NULL AND salaried_period_amount_minor IS NULL) OR (compensation_basis = 'SALARIED' AND salaried_period_amount_minor IS NOT NULL AND hourly_rate_minor IS NULL)", name='ck_employee_compensation_terms_basis_matches_amount'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['restaurant_role_id'], ['restaurant_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'function_label', 'valid_from')
    )
    op.create_index(op.f('ix_employee_compensation_terms_employee_id'), 'employee_compensation_terms', ['employee_id'], unique=False)
    op.create_table('payroll_import_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_run_id', sa.Integer(), nullable=False),
    sa.Column('issue_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['import_run_id'], ['payroll_import_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_import_issues_import_run_id'), 'payroll_import_issues', ['import_run_id'], unique=False)
    op.create_table('payroll_provider_employee_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('external_employee_key', sa.String(length=255), nullable=False),
    sa.Column('external_display_reference', sa.String(length=255), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('mapping_status', sa.String(length=16), nullable=False),
    sa.Column('resolution_method', sa.String(length=64), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system_id', 'restaurant_id', 'external_employee_key')
    )
    op.create_index(op.f('ix_payroll_provider_employee_identities_employee_id'), 'payroll_provider_employee_identities', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_provider_employee_identities_restaurant_id'), 'payroll_provider_employee_identities', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_payroll_provider_employee_identities_source_system_id'), 'payroll_provider_employee_identities', ['source_system_id'], unique=False)
    op.create_table('employee_payroll_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_run_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('compensation_term_id', sa.Integer(), nullable=True),
    sa.Column('source_pay_frequency_label', sa.String(length=64), nullable=True),
    sa.Column('review_status', sa.String(length=32), nullable=True),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['compensation_term_id'], ['employee_compensation_terms.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payroll_run_id', 'employee_id')
    )
    op.create_index(op.f('ix_employee_payroll_results_employee_id'), 'employee_payroll_results', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_payroll_results_payroll_run_id'), 'employee_payroll_results', ['payroll_run_id'], unique=False)
    op.create_table('payroll_earning_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_payroll_result_id', sa.Integer(), nullable=False),
    sa.Column('earning_type', sa.String(length=64), nullable=False),
    sa.Column('source_label', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('rate_minor', sa.Integer(), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('paid_to_employee', sa.Boolean(), nullable=False),
    sa.Column('excluded_from_taxable_wages', sa.Boolean(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_payroll_result_id'], ['employee_payroll_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_earning_facts_employee_payroll_result_id'), 'payroll_earning_facts', ['employee_payroll_result_id'], unique=False)
    op.create_table('payroll_employer_liability_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_payroll_result_id', sa.Integer(), nullable=False),
    sa.Column('liability_type', sa.String(length=64), nullable=False),
    sa.Column('source_label', sa.String(length=255), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_payroll_result_id'], ['employee_payroll_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_employer_liability_facts_employee_payroll_result_id'), 'payroll_employer_liability_facts', ['employee_payroll_result_id'], unique=False)
    op.create_table('payroll_payment_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_payroll_result_id', sa.Integer(), nullable=False),
    sa.Column('pay_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payment_method', sa.String(length=64), nullable=True),
    sa.Column('payment_amount_minor', sa.Integer(), nullable=False),
    sa.Column('provider_payment_reference', sa.String(length=255), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_payroll_result_id'], ['employee_payroll_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_payment_facts_employee_payroll_result_id'), 'payroll_payment_facts', ['employee_payroll_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payroll_payment_facts_employee_payroll_result_id'), table_name='payroll_payment_facts')
    op.drop_table('payroll_payment_facts')
    op.drop_index(op.f('ix_payroll_employer_liability_facts_employee_payroll_result_id'), table_name='payroll_employer_liability_facts')
    op.drop_table('payroll_employer_liability_facts')
    op.drop_index(op.f('ix_payroll_earning_facts_employee_payroll_result_id'), table_name='payroll_earning_facts')
    op.drop_table('payroll_earning_facts')
    op.drop_index(op.f('ix_employee_payroll_results_payroll_run_id'), table_name='employee_payroll_results')
    op.drop_index(op.f('ix_employee_payroll_results_employee_id'), table_name='employee_payroll_results')
    op.drop_table('employee_payroll_results')
    op.drop_index(op.f('ix_payroll_provider_employee_identities_source_system_id'), table_name='payroll_provider_employee_identities')
    op.drop_index(op.f('ix_payroll_provider_employee_identities_restaurant_id'), table_name='payroll_provider_employee_identities')
    op.drop_index(op.f('ix_payroll_provider_employee_identities_employee_id'), table_name='payroll_provider_employee_identities')
    op.drop_table('payroll_provider_employee_identities')
    op.drop_index(op.f('ix_payroll_import_issues_import_run_id'), table_name='payroll_import_issues')
    op.drop_table('payroll_import_issues')
    op.drop_index(op.f('ix_employee_compensation_terms_employee_id'), table_name='employee_compensation_terms')
    op.drop_table('employee_compensation_terms')
    op.drop_index(op.f('ix_payroll_import_runs_source_system_id'), table_name='payroll_import_runs')
    op.drop_index(op.f('ix_payroll_import_runs_restaurant_id'), table_name='payroll_import_runs')
    op.drop_table('payroll_import_runs')
    op.drop_index(op.f('ix_payroll_runs_source_system_id'), table_name='payroll_runs')
    op.drop_index(op.f('ix_payroll_runs_restaurant_id'), table_name='payroll_runs')
    op.drop_table('payroll_runs')
    op.drop_index(op.f('ix_workweek_definitions_restaurant_id'), table_name='workweek_definitions')
    op.drop_table('workweek_definitions')
    op.drop_index(op.f('ix_payroll_schedules_restaurant_id'), table_name='payroll_schedules')
    op.drop_table('payroll_schedules')
    # ### end Alembic commands ###
