"""add payroll calculation engine schema

Revision ID: 6ab2b01f7172
Revises: 2747004fc651
Create Date: 2026-09-08 19:21:19.944117

Adds the RF-One internal Payroll Calculation Engine (Product Owner
decisions: corrected Option C; multi-rate earning lines; Legal Entity
separation, corrected again to use the canonical `LegalEntity` model instead
of `Restaurant`) — `payroll_calculation_runs` (scoped by `legal_entity_id`,
required), `employee_payroll_calculations` (the employee-level summary,
Legal Entity inherited via `calculation_run_id` — never duplicated here),
and `employee_payroll_calculation_earning_lines`. This represents RF-One's
own EXPECTED payroll calculation and is distinct from the existing,
unchanged Payroll domain (`payroll_runs`/`employee_payroll_results`), which
continues to represent the actual payroll processed by the external
provider (ADP) and is still scoped by `restaurant_id` (unchanged — a
separate future assessment, not part of this task).

This migration was rewritten in place (not superseded by a new one) because
this feature had not yet been committed or deployed — see the Payroll
Calculation Engine task reports.

Autogenerate also detected pre-existing, unrelated drift on Selection tables
(`applications`, `in_person_interview_plans`, `phone_interview_plans`) and
the `employee_compensation_terms.legal_entity_id` change (a separate,
already-approved/committed table — see the next migration) — neither is
included here; this migration only adds the three Payroll Calculation
Engine tables and their indexes.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ab2b01f7172'
down_revision: Union[str, Sequence[str], None] = '2747004fc651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_calculation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_entity_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('OPEN', 'CALCULATED')", name='ck_payroll_calculation_runs_status'),
    sa.CheckConstraint('period_end >= period_start', name='ck_payroll_calculation_runs_period'),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_calculation_runs_legal_entity_id'), 'payroll_calculation_runs', ['legal_entity_id'], unique=False)
    op.create_table('employee_payroll_calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calculation_run_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('regular_hours', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('regular_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tips_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bonus_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('bonus_amount >= 0', name='ck_employee_payroll_calc_bonus_amount'),
    sa.CheckConstraint('regular_hours >= 0', name='ck_employee_payroll_calc_regular_hours'),
    sa.CheckConstraint('regular_pay >= 0', name='ck_employee_payroll_calc_regular_pay'),
    sa.CheckConstraint('tips_amount >= 0', name='ck_employee_payroll_calc_tips_amount'),
    sa.ForeignKeyConstraint(['calculation_run_id'], ['payroll_calculation_runs.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calculation_run_id', 'employee_id', name='uq_employee_payroll_calculation')
    )
    op.create_index(op.f('ix_employee_payroll_calculations_calculation_run_id'), 'employee_payroll_calculations', ['calculation_run_id'], unique=False)
    op.create_index(op.f('ix_employee_payroll_calculations_employee_id'), 'employee_payroll_calculations', ['employee_id'], unique=False)
    op.create_table('employee_payroll_calculation_earning_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_payroll_calculation_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=True),
    sa.Column('compensation_term_id', sa.Integer(), nullable=False),
    sa.Column('regular_hours', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('hourly_rate_used', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('regular_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('hourly_rate_used >= 0', name='ck_employee_payroll_calc_line_hourly_rate'),
    sa.CheckConstraint('regular_hours >= 0', name='ck_employee_payroll_calc_line_regular_hours'),
    sa.CheckConstraint('regular_pay >= 0', name='ck_employee_payroll_calc_line_regular_pay'),
    sa.ForeignKeyConstraint(['compensation_term_id'], ['employee_compensation_terms.id'], ),
    sa.ForeignKeyConstraint(['employee_payroll_calculation_id'], ['employee_payroll_calculations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_payroll_calculation_earning_lines_compensation_term_id'), 'employee_payroll_calculation_earning_lines', ['compensation_term_id'], unique=False)
    op.create_index(op.f('ix_employee_payroll_calculation_earning_lines_employee_payroll_calculation_id'), 'employee_payroll_calculation_earning_lines', ['employee_payroll_calculation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_payroll_calculation_earning_lines_employee_payroll_calculation_id'), table_name='employee_payroll_calculation_earning_lines')
    op.drop_index(op.f('ix_employee_payroll_calculation_earning_lines_compensation_term_id'), table_name='employee_payroll_calculation_earning_lines')
    op.drop_table('employee_payroll_calculation_earning_lines')
    op.drop_index(op.f('ix_employee_payroll_calculations_employee_id'), table_name='employee_payroll_calculations')
    op.drop_index(op.f('ix_employee_payroll_calculations_calculation_run_id'), table_name='employee_payroll_calculations')
    op.drop_table('employee_payroll_calculations')
    op.drop_index(op.f('ix_payroll_calculation_runs_legal_entity_id'), table_name='payroll_calculation_runs')
    op.drop_table('payroll_calculation_runs')
    # ### end Alembic commands ###
