"""add source roles and employee source roles

Revision ID: 7afe7c953207
Revises: 9516f3bd1495
Create Date: 2026-08-26 09:13:03.688869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7afe7c953207'
down_revision: Union[str, Sequence[str], None] = '9516f3bd1495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('source_role_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_system_role', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system_id', 'source_role_id')
    )
    op.create_table('employee_source_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('source_role_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['source_role_id'], ['source_roles.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'source_role_id')
    )
    op.create_index(op.f('ix_employee_source_roles_employee_id'), 'employee_source_roles', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_source_roles_source_role_id'), 'employee_source_roles', ['source_role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_source_roles_source_role_id'), table_name='employee_source_roles')
    op.drop_index(op.f('ix_employee_source_roles_employee_id'), table_name='employee_source_roles')
    op.drop_table('employee_source_roles')
    op.drop_table('source_roles')
    # ### end Alembic commands ###
