"""add training tables

Revision ID: 8f933b662969
Revises: 854c3816ffd5
Create Date: 2026-09-10 13:21:06.705278

Adds the Training domain's first operational schema (staff dish/wine "pill"
learning — 03 Software/Training/): `training_accounts` (Training's own
login record — username/password hash/role, linked 1:1 to the shared
`acting_identities` roster), `training_pills` (assignable study units,
metadata only — the actual content stays the single canonical copy in
`RF-One-Training.html`), `training_questions` (the static self-check/
final-quiz/overall-quiz question bank), `training_needs`, `training_
assignments` (one pill assigned against one need), `training_attempts`
(graded final-quiz submissions) and `training_overall_attempts` (graded
whole-path quiz submissions). Purely additive — no existing table is
altered.

Autogenerate also detected pre-existing, unrelated drift on Selection
tables (`applications`, `in_person_interview_plans`, `phone_interview_
plans`) — same drift already called out and excluded by the immediately
preceding migration's own docstring; still excluded here for the same
reason (this migration must not touch Selection).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f933b662969'
down_revision: Union[str, Sequence[str], None] = '854c3816ffd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_pills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('learning_objectives', sa.Text(), nullable=False),
    sa.Column('content_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_pills_slug'), 'training_pills', ['slug'], unique=True)
    op.create_table('training_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acting_identity_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_account_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('trainer', 'student')", name='ck_training_account_role'),
    sa.ForeignKeyConstraint(['acting_identity_id'], ['acting_identities.id'], ),
    sa.ForeignKeyConstraint(['created_by_account_id'], ['training_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('acting_identity_id')
    )
    op.create_index(op.f('ix_training_accounts_username'), 'training_accounts', ['username'], unique=True)
    op.create_table('training_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pill_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=False),
    sa.Column('correct_index', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.CheckConstraint("category IN ('ingredients', 'sales_pairing', 'allergen_warning')", name='ck_training_question_category'),
    sa.CheckConstraint("kind IN ('self_check', 'final_quiz', 'overall_quiz')", name='ck_training_question_kind'),
    sa.CheckConstraint('correct_index IN (0, 1, 2)', name='ck_training_question_correct_index'),
    sa.ForeignKeyConstraint(['pill_id'], ['training_pills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pill_id', 'kind', 'position', name='uq_training_question_pill_kind_position')
    )
    op.create_index(op.f('ix_training_questions_pill_id'), 'training_questions', ['pill_id'], unique=False)
    op.create_table('training_needs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_account_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('origin', sa.String(length=24), nullable=True),
    sa.Column('created_by_account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("origin IS NULL OR origin IN ('selection', 'observation', 'sales', 'other')", name='ck_training_need_origin'),
    sa.ForeignKeyConstraint(['created_by_account_id'], ['training_accounts.id'], ),
    sa.ForeignKeyConstraint(['student_account_id'], ['training_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_needs_student_account_id'), 'training_needs', ['student_account_id'], unique=False)
    op.create_table('training_overall_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_account_id', sa.Integer(), nullable=False),
    sa.Column('pills_json', sa.Text(), nullable=False),
    sa.Column('questions_json', sa.Text(), nullable=False),
    sa.Column('answers_json', sa.Text(), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('points_possible', sa.Integer(), nullable=False),
    sa.Column('submission_token', sa.String(length=64), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['student_account_id'], ['training_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_token')
    )
    op.create_index(op.f('ix_training_overall_attempts_student_account_id'), 'training_overall_attempts', ['student_account_id'], unique=False)
    op.create_table('training_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('need_id', sa.Integer(), nullable=False),
    sa.Column('pill_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_account_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('first_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_account_id'], ['training_accounts.id'], ),
    sa.ForeignKeyConstraint(['need_id'], ['training_needs.id'], ),
    sa.ForeignKeyConstraint(['pill_id'], ['training_pills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('need_id', 'pill_id', name='uq_training_assignment_need_pill')
    )
    op.create_index(op.f('ix_training_assignments_need_id'), 'training_assignments', ['need_id'], unique=False)
    op.create_index(op.f('ix_training_assignments_pill_id'), 'training_assignments', ['pill_id'], unique=False)
    op.create_table('training_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('student_account_id', sa.Integer(), nullable=False),
    sa.Column('pill_id', sa.Integer(), nullable=False),
    sa.Column('pill_content_version', sa.Integer(), nullable=False),
    sa.Column('quiz_version', sa.Integer(), nullable=False),
    sa.Column('questions_json', sa.Text(), nullable=False),
    sa.Column('answers_json', sa.Text(), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('points_possible', sa.Integer(), nullable=False),
    sa.Column('submission_token', sa.String(length=64), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['training_assignments.id'], ),
    sa.ForeignKeyConstraint(['pill_id'], ['training_pills.id'], ),
    sa.ForeignKeyConstraint(['student_account_id'], ['training_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_token')
    )
    op.create_index(op.f('ix_training_attempts_assignment_id'), 'training_attempts', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_training_attempts_student_account_id'), 'training_attempts', ['student_account_id'], unique=False)
    # ### end Alembic commands ### (pre-existing, unrelated Selection drift on
    # applications/in_person_interview_plans/phone_interview_plans deliberately
    # excluded — see this migration's own docstring)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_attempts_student_account_id'), table_name='training_attempts')
    op.drop_index(op.f('ix_training_attempts_assignment_id'), table_name='training_attempts')
    op.drop_table('training_attempts')
    op.drop_index(op.f('ix_training_assignments_pill_id'), table_name='training_assignments')
    op.drop_index(op.f('ix_training_assignments_need_id'), table_name='training_assignments')
    op.drop_table('training_assignments')
    op.drop_index(op.f('ix_training_overall_attempts_student_account_id'), table_name='training_overall_attempts')
    op.drop_table('training_overall_attempts')
    op.drop_index(op.f('ix_training_needs_student_account_id'), table_name='training_needs')
    op.drop_table('training_needs')
    op.drop_index(op.f('ix_training_questions_pill_id'), table_name='training_questions')
    op.drop_table('training_questions')
    op.drop_index(op.f('ix_training_accounts_username'), table_name='training_accounts')
    op.drop_table('training_accounts')
    op.drop_index(op.f('ix_training_pills_slug'), table_name='training_pills')
    op.drop_table('training_pills')
    # ### end Alembic commands ###
