"""add purchasing schema

Revision ID: 93df95757d5e
Revises: 47b3d9bb8108
Create Date: 2026-08-30 14:12:28.795051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93df95757d5e'
down_revision: Union[str, Sequence[str], None] = '47b3d9bb8108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('acquisition_methods', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_restaurant_id'), 'suppliers', ['restaurant_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.create_table('supplier_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('supplier_code', sa.String(length=128), nullable=True),
    sa.Column('supplier_name', sa.String(length=500), nullable=True),
    sa.Column('packaging', sa.String(length=255), nullable=True),
    sa.Column('economic_classification', sa.String(length=16), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'supplier_code')
    )
    op.create_index(op.f('ix_supplier_products_supplier_id'), 'supplier_products', ['supplier_id'], unique=False)
    op.create_table('purchase_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('document_number', sa.String(length=128), nullable=True),
    sa.Column('document_type', sa.String(length=32), nullable=False),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('destination_location', sa.String(length=500), nullable=True),
    sa.Column('customer_account_reference', sa.String(length=255), nullable=True),
    sa.Column('acquisition_method', sa.String(length=32), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('total_amount_minor', sa.Integer(), nullable=True),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('source_reference', sa.String(length=1024), nullable=True),
    sa.Column('source_provenance', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_documents_supplier_id'), 'purchase_documents', ['supplier_id'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('supplier_product_id', sa.Integer(), nullable=True),
    sa.Column('item_description', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_product_id'], ['supplier_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_lines_purchase_order_id'), 'purchase_order_lines', ['purchase_order_id'], unique=False)
    op.create_table('configured_expectations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_product_id', sa.Integer(), nullable=False),
    sa.Column('acceptable_configurations', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approved_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['supplier_product_id'], ['supplier_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configured_expectations_supplier_product_id'), 'configured_expectations', ['supplier_product_id'], unique=False)
    op.create_table('purchase_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_document_id', sa.Integer(), nullable=False),
    sa.Column('line_type', sa.String(length=16), nullable=False),
    sa.Column('source_line_number', sa.Integer(), nullable=True),
    sa.Column('raw_description', sa.String(length=1000), nullable=False),
    sa.Column('source_amount_minor', sa.Integer(), nullable=True),
    sa.Column('supplier_product_id', sa.Integer(), nullable=True),
    sa.Column('supplier_item_code', sa.String(length=128), nullable=True),
    sa.Column('supplier_category_code', sa.String(length=128), nullable=True),
    sa.Column('source_section', sa.String(length=255), nullable=True),
    sa.Column('manufacturer_code', sa.String(length=128), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('purchase_unit', sa.String(length=32), nullable=True),
    sa.Column('pack_count', sa.Integer(), nullable=True),
    sa.Column('pack_size', sa.String(length=64), nullable=True),
    sa.Column('product_variant', sa.String(length=255), nullable=True),
    sa.Column('grade', sa.String(length=128), nullable=True),
    sa.Column('unit_price_minor', sa.Integer(), nullable=True),
    sa.Column('economic_classification', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("line_type = 'PRODUCT' OR economic_classification IS NULL", name='ck_purchase_lines_classification_requires_product_type'),
    sa.CheckConstraint("line_type = 'PRODUCT' OR supplier_product_id IS NULL", name='ck_purchase_lines_supplier_product_requires_product_type'),
    sa.CheckConstraint("line_type IN ('PRODUCT', 'SURCHARGE', 'DISCOUNT')", name='ck_purchase_lines_line_type'),
    sa.ForeignKeyConstraint(['purchase_document_id'], ['purchase_documents.id'], ),
    sa.ForeignKeyConstraint(['supplier_product_id'], ['supplier_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_lines_purchase_document_id'), 'purchase_lines', ['purchase_document_id'], unique=False)
    op.create_table('receiving_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('purchase_document_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('receiving_user_employee_id', sa.Integer(), nullable=True),
    sa.Column('receiving_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capture_method', sa.String(length=16), nullable=False),
    sa.Column('source_provenance', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("capture_method IN ('LABEL_BASED', 'ORDER_BASED', 'MANUAL')", name='ck_receiving_records_capture_method'),
    sa.CheckConstraint("status IN ('IN_PROGRESS', 'COMPLETED')", name='ck_receiving_records_status'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['purchase_document_id'], ['purchase_documents.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['receiving_user_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receiving_records_supplier_id'), 'receiving_records', ['supplier_id'], unique=False)
    op.create_table('purchasing_validation_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_document_id', sa.Integer(), nullable=False),
    sa.Column('purchase_line_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('human_decision', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("severity IN ('INFORMATION', 'WARNING', 'ERROR')", name='ck_purchasing_validation_log_entries_severity'),
    sa.CheckConstraint("status IN ('OPEN', 'APPROVED', 'REJECTED', 'CLOSED')", name='ck_purchasing_validation_log_entries_status'),
    sa.ForeignKeyConstraint(['purchase_document_id'], ['purchase_documents.id'], ),
    sa.ForeignKeyConstraint(['purchase_line_id'], ['purchase_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchasing_validation_log_entries_purchase_document_id'), 'purchasing_validation_log_entries', ['purchase_document_id'], unique=False)
    op.create_table('receiving_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receiving_record_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_line_id', sa.Integer(), nullable=True),
    sa.Column('purchase_line_id', sa.Integer(), nullable=True),
    sa.Column('supplier_product_id', sa.Integer(), nullable=True),
    sa.Column('raw_description', sa.String(length=1000), nullable=True),
    sa.Column('observed_quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('observed_pack_count', sa.Integer(), nullable=True),
    sa.Column('observed_pack_size', sa.String(length=64), nullable=True),
    sa.Column('observed_unit', sa.String(length=32), nullable=True),
    sa.Column('observed_brand', sa.String(length=255), nullable=True),
    sa.Column('observed_variant', sa.String(length=255), nullable=True),
    sa.Column('observed_grade', sa.String(length=128), nullable=True),
    sa.Column('damaged_quantity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('photo_evidence', sa.String(length=1024), nullable=True),
    sa.Column('capture_method', sa.String(length=24), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('damaged_quantity IS NULL OR damaged_quantity = 0 OR photo_evidence IS NOT NULL', name='ck_receiving_lines_damaged_requires_photo'),
    sa.CheckConstraint('purchase_order_line_id IS NOT NULL OR photo_evidence IS NOT NULL', name='ck_receiving_lines_extra_item_requires_photo'),
    sa.ForeignKeyConstraint(['purchase_line_id'], ['purchase_lines.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_lines.id'], ),
    sa.ForeignKeyConstraint(['receiving_record_id'], ['receiving_records.id'], ),
    sa.ForeignKeyConstraint(['supplier_product_id'], ['supplier_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receiving_lines_receiving_record_id'), 'receiving_lines', ['receiving_record_id'], unique=False)
    op.create_table('purchasing_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=24), nullable=False),
    sa.Column('purchase_document_id', sa.Integer(), nullable=True),
    sa.Column('purchase_line_id', sa.Integer(), nullable=True),
    sa.Column('supplier_product_id', sa.Integer(), nullable=True),
    sa.Column('purchase_order_line_id', sa.Integer(), nullable=True),
    sa.Column('receiving_record_id', sa.Integer(), nullable=True),
    sa.Column('receiving_line_id', sa.Integer(), nullable=True),
    sa.Column('comparison_basis', sa.String(length=24), nullable=True),
    sa.Column('expected_configuration', sa.JSON(), nullable=True),
    sa.Column('observed_configuration', sa.JSON(), nullable=True),
    sa.Column('reconciliation_context', sa.Text(), nullable=True),
    sa.Column('responsible_user_employee_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('human_decision', sa.String(length=32), nullable=True),
    sa.Column('decided_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("comparison_basis IS NULL OR comparison_basis IN ('CONFIGURED_EXPECTATION', 'PREVIOUS_PURCHASE')", name='ck_purchasing_alerts_comparison_basis'),
    sa.CheckConstraint("status IN ('OPEN', 'ACKNOWLEDGED', 'DECIDED', 'CLOSED')", name='ck_purchasing_alerts_status'),
    sa.CheckConstraint("trigger IN ('CONFIGURATION_DEVIATION', 'RECEIVING_DISCREPANCY')", name='ck_purchasing_alerts_trigger'),
    sa.ForeignKeyConstraint(['decided_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['purchase_document_id'], ['purchase_documents.id'], ),
    sa.ForeignKeyConstraint(['purchase_line_id'], ['purchase_lines.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_lines.id'], ),
    sa.ForeignKeyConstraint(['receiving_line_id'], ['receiving_lines.id'], ),
    sa.ForeignKeyConstraint(['receiving_record_id'], ['receiving_records.id'], ),
    sa.ForeignKeyConstraint(['responsible_user_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['supplier_product_id'], ['supplier_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchasing_alerts_purchase_document_id'), 'purchasing_alerts', ['purchase_document_id'], unique=False)
    op.create_table('expected_supplier_credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('purchase_document_id', sa.Integer(), nullable=False),
    sa.Column('purchase_line_id', sa.Integer(), nullable=False),
    sa.Column('rejected_quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('expected_amount_minor', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('OPEN', 'PARTIALLY_RESOLVED', 'RESOLVED')", name='ck_expected_supplier_credits_status'),
    sa.ForeignKeyConstraint(['alert_id'], ['purchasing_alerts.id'], ),
    sa.ForeignKeyConstraint(['purchase_document_id'], ['purchase_documents.id'], ),
    sa.ForeignKeyConstraint(['purchase_line_id'], ['purchase_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expected_supplier_credits_alert_id'), 'expected_supplier_credits', ['alert_id'], unique=False)
    op.create_table('supplier_credit_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expected_supplier_credit_id', sa.Integer(), nullable=False),
    sa.Column('purchase_document_id', sa.Integer(), nullable=True),
    sa.Column('purchase_line_id', sa.Integer(), nullable=True),
    sa.Column('applied_amount_minor', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['expected_supplier_credit_id'], ['expected_supplier_credits.id'], ),
    sa.ForeignKeyConstraint(['purchase_document_id'], ['purchase_documents.id'], ),
    sa.ForeignKeyConstraint(['purchase_line_id'], ['purchase_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_credit_references_expected_supplier_credit_id'), 'supplier_credit_references', ['expected_supplier_credit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_credit_references_expected_supplier_credit_id'), table_name='supplier_credit_references')
    op.drop_table('supplier_credit_references')
    op.drop_index(op.f('ix_expected_supplier_credits_alert_id'), table_name='expected_supplier_credits')
    op.drop_table('expected_supplier_credits')
    op.drop_index(op.f('ix_purchasing_alerts_purchase_document_id'), table_name='purchasing_alerts')
    op.drop_table('purchasing_alerts')
    op.drop_index(op.f('ix_receiving_lines_receiving_record_id'), table_name='receiving_lines')
    op.drop_table('receiving_lines')
    op.drop_index(op.f('ix_purchasing_validation_log_entries_purchase_document_id'), table_name='purchasing_validation_log_entries')
    op.drop_table('purchasing_validation_log_entries')
    op.drop_index(op.f('ix_receiving_records_supplier_id'), table_name='receiving_records')
    op.drop_table('receiving_records')
    op.drop_index(op.f('ix_purchase_lines_purchase_document_id'), table_name='purchase_lines')
    op.drop_table('purchase_lines')
    op.drop_index(op.f('ix_configured_expectations_supplier_product_id'), table_name='configured_expectations')
    op.drop_table('configured_expectations')
    op.drop_index(op.f('ix_purchase_order_lines_purchase_order_id'), table_name='purchase_order_lines')
    op.drop_table('purchase_order_lines')
    op.drop_index(op.f('ix_purchase_documents_supplier_id'), table_name='purchase_documents')
    op.drop_table('purchase_documents')
    op.drop_index(op.f('ix_supplier_products_supplier_id'), table_name='supplier_products')
    op.drop_table('supplier_products')
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_suppliers_restaurant_id'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
