"""baseline canonical restaurant schema

Revision ID: 9516f3bd1495
Revises: 
Create Date: 2026-08-26 05:51:46.047089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9516f3bd1495'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=True),
    sa.Column('source_merchant_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system_id', 'source_merchant_id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=True),
    sa.Column('source_location_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system_id', 'source_location_id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('source_category_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system_id', 'source_category_id')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('source_device_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('device_type', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system_id', 'source_device_id')
    )
    op.create_table('discount_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('source_discount_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system_id', 'source_discount_id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=True),
    sa.Column('source_employee_id', sa.String(length=128), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('custom_id', sa.String(length=64), nullable=True),
    sa.Column('system_role', sa.String(length=32), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('source_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system_id', 'source_employee_id')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('source_item_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=True),
    sa.Column('code', sa.String(length=128), nullable=True),
    sa.Column('current_price', sa.Integer(), nullable=True),
    sa.Column('price_without_vat', sa.Integer(), nullable=True),
    sa.Column('price_type', sa.String(length=32), nullable=True),
    sa.Column('item_type', sa.String(length=32), nullable=True),
    sa.Column('item_nature', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('source_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system_id', 'source_item_id')
    )
    op.create_table('modifier_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('source_modifier_group_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system_id', 'source_modifier_group_id')
    )
    op.create_table('order_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=True),
    sa.Column('source_order_type_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('min_order_amount', sa.Integer(), nullable=True),
    sa.Column('max_order_amount', sa.Integer(), nullable=True),
    sa.Column('configured_fee', sa.Integer(), nullable=True),
    sa.Column('average_order_time', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system_id', 'source_order_type_id')
    )
    op.create_table('physical_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('table_number', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('seat_capacity', sa.Integer(), nullable=True),
    sa.Column('area', sa.String(length=128), nullable=True),
    sa.Column('indoor_outdoor', sa.String(length=32), nullable=True),
    sa.Column('section', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('declared_guest_count', sa.Integer(), nullable=True),
    sa.Column('derived_guest_count', sa.Integer(), nullable=True),
    sa.Column('declared_guest_count_source', sa.String(length=32), nullable=True),
    sa.Column('reconstruction_status', sa.String(length=32), nullable=True),
    sa.Column('reconstruction_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_services_opened_at'), 'table_services', ['opened_at'], unique=False)
    op.create_table('tax_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('source_tax_rate_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system_id', 'source_tax_rate_id')
    )
    op.create_table('tenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('source_tender_id', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system_id', 'source_tender_id')
    )
    op.create_table('item_categories',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'category_id')
    )
    op.create_table('modifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('modifier_group_id', sa.Integer(), nullable=True),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('source_modifier_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('alternate_name', sa.String(length=255), nullable=True),
    sa.Column('price_delta', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['modifier_group_id'], ['modifier_groups.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system_id', 'source_modifier_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('table_service_id', sa.Integer(), nullable=True),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('source_order_id', sa.String(length=128), nullable=False),
    sa.Column('source_employee_id', sa.String(length=128), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('order_type_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('device_source_id', sa.String(length=128), nullable=True),
    sa.Column('client_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('payment_state', sa.String(length=32), nullable=True),
    sa.Column('pay_type', sa.String(length=32), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('subtotal', sa.Integer(), nullable=True),
    sa.Column('discount_total', sa.Integer(), nullable=True),
    sa.Column('tax_total', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('title_raw', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('test_mode', sa.Boolean(), nullable=True),
    sa.Column('manual_transaction', sa.Boolean(), nullable=True),
    sa.Column('tax_removed', sa.Boolean(), nullable=True),
    sa.Column('is_vat', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['order_type_id'], ['order_types.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.ForeignKeyConstraint(['table_service_id'], ['table_services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system_id', 'source_order_id')
    )
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_employee_id'), 'orders', ['employee_id'], unique=False)
    op.create_index(op.f('ix_orders_table_service_id'), 'orders', ['table_service_id'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=True),
    sa.Column('source_shift_id', sa.String(length=128), nullable=True),
    sa.Column('clock_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clock_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('override_in_employee_id', sa.Integer(), nullable=True),
    sa.Column('override_in_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('override_out_employee_id', sa.Integer(), nullable=True),
    sa.Column('override_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('server_banking', sa.Boolean(), nullable=True),
    sa.Column('source_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['override_in_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['override_out_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system_id', 'source_shift_id')
    )
    op.create_index(op.f('ix_shifts_clock_in'), 'shifts', ['clock_in'], unique=False)
    op.create_index(op.f('ix_shifts_employee_id'), 'shifts', ['employee_id'], unique=False)
    op.create_table('source_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_hash', sa.String(length=128), nullable=True),
    sa.Column('raw_path', sa.String(length=1024), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_records_system_entity_source', 'source_records', ['source_system_id', 'entity_type', 'source_id'], unique=False)
    op.create_table('table_service_employees',
    sa.Column('table_service_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['table_service_id'], ['table_services.id'], ),
    sa.PrimaryKeyConstraint('table_service_id', 'employee_id')
    )
    op.create_table('table_service_physical_tables',
    sa.Column('table_service_id', sa.Integer(), nullable=False),
    sa.Column('physical_table_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['physical_table_id'], ['physical_tables.id'], ),
    sa.ForeignKeyConstraint(['table_service_id'], ['table_services.id'], ),
    sa.PrimaryKeyConstraint('table_service_id', 'physical_table_id')
    )
    op.create_table('item_modifiers',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('modifier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['modifier_id'], ['modifiers.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'modifier_id')
    )
    op.create_table('order_discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('discount_definition_id', sa.Integer(), nullable=True),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('source_discount_id', sa.String(length=128), nullable=True),
    sa.Column('name_raw', sa.String(length=255), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('raw_shape_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['discount_definition_id'], ['discount_definitions.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('source_fee_id', sa.String(length=128), nullable=True),
    sa.Column('source_line_item_id', sa.String(length=128), nullable=True),
    sa.Column('fee_type', sa.String(length=64), nullable=True),
    sa.Column('name_raw', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('source_line_item_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('quantity_decimal_digits', sa.Integer(), nullable=True),
    sa.Column('unit_name', sa.String(length=64), nullable=True),
    sa.Column('historical_unit_price', sa.Integer(), nullable=True),
    sa.Column('guest_number', sa.Integer(), nullable=True),
    sa.Column('guest_label_raw', sa.String(length=255), nullable=True),
    sa.Column('item_code_raw', sa.String(length=128), nullable=True),
    sa.Column('is_revenue', sa.Boolean(), nullable=True),
    sa.Column('is_order_fee', sa.Boolean(), nullable=True),
    sa.Column('printed', sa.Boolean(), nullable=True),
    sa.Column('refunded_flag', sa.Boolean(), nullable=True),
    sa.Column('exchanged_flag', sa.Boolean(), nullable=True),
    sa.Column('line_item_info_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system_id', 'source_line_item_id')
    )
    op.create_index(op.f('ix_order_items_created_at'), 'order_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_items_guest_number'), 'order_items', ['guest_number'], unique=False)
    op.create_index(op.f('ix_order_items_item_id'), 'order_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('source_payment_id', sa.String(length=128), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('source_employee_id', sa.String(length=128), nullable=True),
    sa.Column('tender_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('device_source_id', sa.String(length=128), nullable=True),
    sa.Column('client_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('tax_amount_source', sa.Integer(), nullable=True),
    sa.Column('cash_tendered', sa.Integer(), nullable=True),
    sa.Column('cashback_amount', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('offline', sa.Boolean(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system_id', 'source_payment_id')
    )
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_employee_id'), 'payments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_table('order_item_discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('discount_definition_id', sa.Integer(), nullable=True),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('source_discount_id', sa.String(length=128), nullable=True),
    sa.Column('name_raw', sa.String(length=255), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('raw_shape_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['discount_definition_id'], ['discount_definitions.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_discounts_order_item_id'), 'order_item_discounts', ['order_item_id'], unique=False)
    op.create_table('order_item_modifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('modifier_id', sa.Integer(), nullable=True),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('source_modification_id', sa.String(length=128), nullable=True),
    sa.Column('name_raw', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['modifier_id'], ['modifiers.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_modifiers_order_item_id'), 'order_item_modifiers', ['order_item_id'], unique=False)
    op.create_table('order_item_taxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('tax_rate_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('rate_applied', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('source_tax_reference', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.ForeignKeyConstraint(['tax_rate_id'], ['tax_rates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_taxes_order_item_id'), 'order_item_taxes', ['order_item_id'], unique=False)
    op.create_table('payment_tips',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('source_present', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('source_refund_id', sa.String(length=128), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('device_source_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('tax_amount', sa.Integer(), nullable=True),
    sa.Column('tip_amount', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('voided', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system_id', 'source_refund_id')
    )
    op.create_index(op.f('ix_refunds_created_at'), 'refunds', ['created_at'], unique=False)
    op.create_index(op.f('ix_refunds_order_id'), 'refunds', ['order_id'], unique=False)
    op.create_index(op.f('ix_refunds_payment_id'), 'refunds', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refunds_payment_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_order_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_created_at'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_table('payment_tips')
    op.drop_index(op.f('ix_order_item_taxes_order_item_id'), table_name='order_item_taxes')
    op.drop_table('order_item_taxes')
    op.drop_index(op.f('ix_order_item_modifiers_order_item_id'), table_name='order_item_modifiers')
    op.drop_table('order_item_modifiers')
    op.drop_index(op.f('ix_order_item_discounts_order_item_id'), table_name='order_item_discounts')
    op.drop_table('order_item_discounts')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_employee_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_item_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_guest_number'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_created_at'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_table('order_fees')
    op.drop_table('order_discounts')
    op.drop_table('item_modifiers')
    op.drop_table('table_service_physical_tables')
    op.drop_table('table_service_employees')
    op.drop_index('ix_source_records_system_entity_source', table_name='source_records')
    op.drop_table('source_records')
    op.drop_index(op.f('ix_shifts_employee_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_clock_in'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_orders_table_service_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_employee_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('modifiers')
    op.drop_table('item_categories')
    op.drop_table('tenders')
    op.drop_table('tax_rates')
    op.drop_index(op.f('ix_table_services_opened_at'), table_name='table_services')
    op.drop_table('table_services')
    op.drop_table('physical_tables')
    op.drop_table('order_types')
    op.drop_table('modifier_groups')
    op.drop_table('items')
    op.drop_table('ingestion_runs')
    op.drop_table('employees')
    op.drop_table('discount_definitions')
    op.drop_table('devices')
    op.drop_table('categories')
    op.drop_table('locations')
    op.drop_table('merchants')
    op.drop_table('source_systems')
    # ### end Alembic commands ###
