"""add tip policy and calculation schema

Revision ID: dc31a1741fd8
Revises: e6df7aa7d83b
Create Date: 2026-08-26 12:15:04.361651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc31a1741fd8'
down_revision: Union[str, Sequence[str], None] = 'e6df7aa7d83b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tip_calculation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('calculation_version', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tip_calculation_runs_restaurant_id'), 'tip_calculation_runs', ['restaurant_id'], unique=False)
    op.create_table('tip_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tip_policies_restaurant_id'), 'tip_policies', ['restaurant_id'], unique=False)
    op.create_table('tip_policy_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tip_policy_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('recipient_basis', sa.String(length=32), nullable=False),
    sa.Column('restaurant_role_id', sa.Integer(), nullable=True),
    sa.Column('share_percentage', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('split_method', sa.String(length=64), nullable=False),
    sa.Column('no_eligible_behavior', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.CheckConstraint("recipient_basis <> 'ROLE_PRESENT_AT_PAYMENT' OR restaurant_role_id IS NOT NULL", name='ck_tip_policy_components_role_present_requires_role'),
    sa.ForeignKeyConstraint(['restaurant_role_id'], ['restaurant_roles.id'], ),
    sa.ForeignKeyConstraint(['tip_policy_id'], ['tip_policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tip_policy_components_tip_policy_id'), 'tip_policy_components', ['tip_policy_id'], unique=False)
    op.create_table('tip_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calculation_run_id', sa.Integer(), nullable=False),
    sa.Column('payment_tip_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('policy_component_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('allocated_amount_minor', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['calculation_run_id'], ['tip_calculation_runs.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['payment_tip_id'], ['payment_tips.payment_id'], ),
    sa.ForeignKeyConstraint(['policy_component_id'], ['tip_policy_components.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calculation_run_id', 'payment_tip_id', 'policy_component_id', 'employee_id')
    )
    op.create_index(op.f('ix_tip_allocations_calculation_run_id'), 'tip_allocations', ['calculation_run_id'], unique=False)
    op.create_index(op.f('ix_tip_allocations_employee_id'), 'tip_allocations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_tip_allocations_order_id'), 'tip_allocations', ['order_id'], unique=False)
    op.create_index(op.f('ix_tip_allocations_payment_id'), 'tip_allocations', ['payment_id'], unique=False)
    op.create_index(op.f('ix_tip_allocations_payment_tip_id'), 'tip_allocations', ['payment_tip_id'], unique=False)
    op.create_index(op.f('ix_tip_allocations_policy_component_id'), 'tip_allocations', ['policy_component_id'], unique=False)
    op.create_table('tip_calculation_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calculation_run_id', sa.Integer(), nullable=False),
    sa.Column('payment_tip_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('issue_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['calculation_run_id'], ['tip_calculation_runs.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['payment_tip_id'], ['payment_tips.payment_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tip_calculation_issues_calculation_run_id'), 'tip_calculation_issues', ['calculation_run_id'], unique=False)
    op.create_index(op.f('ix_tip_calculation_issues_order_id'), 'tip_calculation_issues', ['order_id'], unique=False)
    op.create_index(op.f('ix_tip_calculation_issues_payment_id'), 'tip_calculation_issues', ['payment_id'], unique=False)
    op.create_index(op.f('ix_tip_calculation_issues_payment_tip_id'), 'tip_calculation_issues', ['payment_tip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tip_calculation_issues_payment_tip_id'), table_name='tip_calculation_issues')
    op.drop_index(op.f('ix_tip_calculation_issues_payment_id'), table_name='tip_calculation_issues')
    op.drop_index(op.f('ix_tip_calculation_issues_order_id'), table_name='tip_calculation_issues')
    op.drop_index(op.f('ix_tip_calculation_issues_calculation_run_id'), table_name='tip_calculation_issues')
    op.drop_table('tip_calculation_issues')
    op.drop_index(op.f('ix_tip_allocations_policy_component_id'), table_name='tip_allocations')
    op.drop_index(op.f('ix_tip_allocations_payment_tip_id'), table_name='tip_allocations')
    op.drop_index(op.f('ix_tip_allocations_payment_id'), table_name='tip_allocations')
    op.drop_index(op.f('ix_tip_allocations_order_id'), table_name='tip_allocations')
    op.drop_index(op.f('ix_tip_allocations_employee_id'), table_name='tip_allocations')
    op.drop_index(op.f('ix_tip_allocations_calculation_run_id'), table_name='tip_allocations')
    op.drop_table('tip_allocations')
    op.drop_index(op.f('ix_tip_policy_components_tip_policy_id'), table_name='tip_policy_components')
    op.drop_table('tip_policy_components')
    op.drop_index(op.f('ix_tip_policies_restaurant_id'), table_name='tip_policies')
    op.drop_table('tip_policies')
    op.drop_index(op.f('ix_tip_calculation_runs_restaurant_id'), table_name='tip_calculation_runs')
    op.drop_table('tip_calculation_runs')
    # ### end Alembic commands ###
