"""add restaurant profile areas roles and employee assignment

Revision ID: e6df7aa7d83b
Revises: 7afe7c953207
Create Date: 2026-08-26 10:10:22.236297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6df7aa7d83b'
down_revision: Union[str, Sequence[str], None] = '7afe7c953207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('default_currency', sa.String(length=8), nullable=True),
    sa.Column('default_timezone', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operational_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'name')
    )
    op.create_index(op.f('ix_operational_areas_restaurant_id'), 'operational_areas', ['restaurant_id'], unique=False)
    op.create_table('physical_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('area_type', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'name')
    )
    op.create_index(op.f('ix_physical_areas_restaurant_id'), 'physical_areas', ['restaurant_id'], unique=False)
    op.create_table('restaurant_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'name')
    )
    op.create_index(op.f('ix_restaurant_roles_restaurant_id'), 'restaurant_roles', ['restaurant_id'], unique=False)
    op.create_table('operational_area_roles',
    sa.Column('operational_area_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['operational_area_id'], ['operational_areas.id'], ),
    sa.ForeignKeyConstraint(['restaurant_role_id'], ['restaurant_roles.id'], ),
    sa.PrimaryKeyConstraint('operational_area_id', 'restaurant_role_id')
    )
    op.create_table('restaurant_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_locations_location_id'), 'restaurant_locations', ['location_id'], unique=False)
    op.create_index(op.f('ix_restaurant_locations_restaurant_id'), 'restaurant_locations', ['restaurant_id'], unique=False)
    op.create_table('employee_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('operational_area_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_role_id', sa.Integer(), nullable=False),
    sa.Column('physical_area_id', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assignment_source', sa.String(length=32), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['operational_area_id'], ['operational_areas.id'], ),
    sa.ForeignKeyConstraint(['physical_area_id'], ['physical_areas.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['restaurant_role_id'], ['restaurant_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'operational_area_id', 'restaurant_role_id', 'valid_from')
    )
    op.create_index(op.f('ix_employee_assignments_employee_id'), 'employee_assignments', ['employee_id'], unique=False)
    op.create_index('ix_employee_assignments_employee_valid_from', 'employee_assignments', ['employee_id', 'valid_from'], unique=False)
    op.create_index(op.f('ix_employee_assignments_operational_area_id'), 'employee_assignments', ['operational_area_id'], unique=False)
    op.create_index(op.f('ix_employee_assignments_restaurant_id'), 'employee_assignments', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_employee_assignments_restaurant_role_id'), 'employee_assignments', ['restaurant_role_id'], unique=False)
    # SQLite cannot ALTER a table to add a foreign key constraint directly
    # (no `ALTER TABLE ... ADD CONSTRAINT` support) — batch mode performs the
    # standard SQLite copy-and-move migration strategy instead, which
    # preserves all existing `physical_tables` rows (task §20: no destructive
    # recreation of populated data).
    with op.batch_alter_table('physical_tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('physical_area_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_physical_tables_physical_area_id_physical_areas',
            'physical_areas',
            ['physical_area_id'],
            ['id'],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('physical_tables', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_physical_tables_physical_area_id_physical_areas', type_='foreignkey'
        )
        batch_op.drop_column('physical_area_id')
    op.drop_index(op.f('ix_employee_assignments_restaurant_role_id'), table_name='employee_assignments')
    op.drop_index(op.f('ix_employee_assignments_restaurant_id'), table_name='employee_assignments')
    op.drop_index(op.f('ix_employee_assignments_operational_area_id'), table_name='employee_assignments')
    op.drop_index('ix_employee_assignments_employee_valid_from', table_name='employee_assignments')
    op.drop_index(op.f('ix_employee_assignments_employee_id'), table_name='employee_assignments')
    op.drop_table('employee_assignments')
    op.drop_index(op.f('ix_restaurant_locations_restaurant_id'), table_name='restaurant_locations')
    op.drop_index(op.f('ix_restaurant_locations_location_id'), table_name='restaurant_locations')
    op.drop_table('restaurant_locations')
    op.drop_table('operational_area_roles')
    op.drop_index(op.f('ix_restaurant_roles_restaurant_id'), table_name='restaurant_roles')
    op.drop_table('restaurant_roles')
    op.drop_index(op.f('ix_physical_areas_restaurant_id'), table_name='physical_areas')
    op.drop_table('physical_areas')
    op.drop_index(op.f('ix_operational_areas_restaurant_id'), table_name='operational_areas')
    op.drop_table('operational_areas')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
